// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: images.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createImage = `-- name: CreateImage :one
INSERT INTO images (
    user_id,
    original_filename,
    original_s3_key,
    mime_type,
    original_size,
    width,
    height
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
RETURNING id, user_id, original_filename, original_s3_key, processed_s3_key, mime_type, original_size, processed_size, width, height, created_at
`

type CreateImageParams struct {
	UserID           uuid.UUID `json:"user_id"`
	OriginalFilename string    `json:"original_filename"`
	OriginalS3Key    string    `json:"original_s3_key"`
	MimeType         string    `json:"mime_type"`
	OriginalSize     int64     `json:"original_size"`
	Width            int32     `json:"width"`
	Height           int32     `json:"height"`
}

func (q *Queries) CreateImage(ctx context.Context, arg CreateImageParams) (Image, error) {
	row := q.db.QueryRowContext(ctx, createImage,
		arg.UserID,
		arg.OriginalFilename,
		arg.OriginalS3Key,
		arg.MimeType,
		arg.OriginalSize,
		arg.Width,
		arg.Height,
	)
	var i Image
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OriginalFilename,
		&i.OriginalS3Key,
		&i.ProcessedS3Key,
		&i.MimeType,
		&i.OriginalSize,
		&i.ProcessedSize,
		&i.Width,
		&i.Height,
		&i.CreatedAt,
	)
	return i, err
}

const deleteImage = `-- name: DeleteImage :exec
DELETE FROM images
WHERE id = $1
`

func (q *Queries) DeleteImage(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteImage, id)
	return err
}

const getImageByID = `-- name: GetImageByID :one
SELECT id, user_id, original_filename, original_s3_key, processed_s3_key, mime_type, original_size, processed_size, width, height, created_at
FROM images
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetImageByID(ctx context.Context, id uuid.UUID) (Image, error) {
	row := q.db.QueryRowContext(ctx, getImageByID, id)
	var i Image
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OriginalFilename,
		&i.OriginalS3Key,
		&i.ProcessedS3Key,
		&i.MimeType,
		&i.OriginalSize,
		&i.ProcessedSize,
		&i.Width,
		&i.Height,
		&i.CreatedAt,
	)
	return i, err
}

const getImagesByUser = `-- name: GetImagesByUser :many
SELECT id, user_id, original_filename, original_s3_key, processed_s3_key, mime_type, original_size, processed_size, width, height, created_at
FROM images
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetImagesByUser(ctx context.Context, userID uuid.UUID) ([]Image, error) {
	rows, err := q.db.QueryContext(ctx, getImagesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Image
	for rows.Next() {
		var i Image
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.OriginalFilename,
			&i.OriginalS3Key,
			&i.ProcessedS3Key,
			&i.MimeType,
			&i.OriginalSize,
			&i.ProcessedSize,
			&i.Width,
			&i.Height,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProcessedImage = `-- name: UpdateProcessedImage :one
UPDATE images
SET
    processed_s3_key = $2,
    processed_size = $3
WHERE id = $1
RETURNING id, user_id, original_filename, original_s3_key, processed_s3_key, mime_type, original_size, processed_size, width, height, created_at
`

type UpdateProcessedImageParams struct {
	ID             uuid.UUID      `json:"id"`
	ProcessedS3Key sql.NullString `json:"processed_s3_key"`
	ProcessedSize  sql.NullInt64  `json:"processed_size"`
}

func (q *Queries) UpdateProcessedImage(ctx context.Context, arg UpdateProcessedImageParams) (Image, error) {
	row := q.db.QueryRowContext(ctx, updateProcessedImage, arg.ID, arg.ProcessedS3Key, arg.ProcessedSize)
	var i Image
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OriginalFilename,
		&i.OriginalS3Key,
		&i.ProcessedS3Key,
		&i.MimeType,
		&i.OriginalSize,
		&i.ProcessedSize,
		&i.Width,
		&i.Height,
		&i.CreatedAt,
	)
	return i, err
}
