// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Image struct {
	ID               uuid.UUID      `json:"id"`
	UserID           uuid.UUID      `json:"user_id"`
	OriginalFilename string         `json:"original_filename"`
	OriginalS3Key    string         `json:"original_s3_key"`
	ProcessedS3Key   sql.NullString `json:"processed_s3_key"`
	MimeType         string         `json:"mime_type"`
	OriginalSize     int64          `json:"original_size"`
	ProcessedSize    sql.NullInt64  `json:"processed_size"`
	Width            int32          `json:"width"`
	Height           int32          `json:"height"`
	CreatedAt        time.Time      `json:"created_at"`
}

type User struct {
	ID           uuid.UUID `json:"id"`
	Username     string    `json:"username"`
	PasswordHash string    `json:"password_hash"`
	CreatedAt    time.Time `json:"created_at"`
}
